"""create orders table

Revision ID: 9a3775382182
Revises: e2aed0f754c0
Create Date: 2026-04-01 00:43:41.283484

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a3775382182'
down_revision: Union[str, Sequence[str], None] = 'e2aed0f754c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'total_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('orders', 'order_status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('orders', 'payment_status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'payment_status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('orders', 'order_status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('orders', 'total_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    # ### end Alembic commands ###
