"""Modified the Tables

Revision ID: a342767cce7a
Revises: 9a3775382182
Create Date: 2026-04-02 00:28:40.819740

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a342767cce7a'
down_revision: Union[str, Sequence[str], None] = '9a3775382182'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Items_Table',
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('item_name', sa.String(), nullable=False),
    sa.Column('item_price', sa.Integer(), nullable=False),
    sa.Column('item_rating', sa.Integer(), nullable=False),
    sa.Column('item_availability', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('item_id')
    )
    op.create_index(op.f('ix_Items_Table_item_id'), 'Items_Table', ['item_id'], unique=False)
    op.create_table('Restaurent_Table',
    sa.Column('Restaurent_id', sa.Integer(), nullable=False),
    sa.Column('Restaurent_name', sa.String(), nullable=False),
    sa.Column('Restaurent_address', sa.String(), nullable=False),
    sa.Column('Restaurent_phone', sa.Integer(), nullable=False),
    sa.Column('Restaurent_rating', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('Restaurent_id')
    )
    op.create_index(op.f('ix_Restaurent_Table_Restaurent_id'), 'Restaurent_Table', ['Restaurent_id'], unique=False)
    op.create_index(op.f('ix_Restaurent_Table_Restaurent_rating'), 'Restaurent_Table', ['Restaurent_rating'], unique=False)
    op.create_table('User_Table',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(), nullable=False),
    sa.Column('user_phone', sa.Integer(), nullable=False),
    sa.Column('user_email', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('Menu_Table',
    sa.Column('cuisine_id', sa.Integer(), nullable=False),
    sa.Column('cuisine_name', sa.String(), nullable=False),
    sa.Column('restaurent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['restaurent_id'], ['Restaurent_Table.Restaurent_id'], ),
    sa.PrimaryKeyConstraint('cuisine_id')
    )
    op.create_table('Orders_Table',
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('order_status', sa.String(), nullable=True),
    sa.Column('payment_status', sa.String(), nullable=True),
    sa.Column('total_amount', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['User_Table.user_id'], ),
    sa.PrimaryKeyConstraint('order_id')
    )
    op.create_index(op.f('ix_Orders_Table_order_id'), 'Orders_Table', ['order_id'], unique=False)
    op.create_index(op.f('ix_Orders_Table_total_amount'), 'Orders_Table', ['total_amount'], unique=False)
    op.drop_index(op.f('ix_orders_order_id'), table_name='orders')
    op.drop_table('orders')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('order_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('item_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('address', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('total_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('order_status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('payment_status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('order_id', name=op.f('orders_pkey'))
    )
    op.create_index(op.f('ix_orders_order_id'), 'orders', ['order_id'], unique=False)
    op.drop_index(op.f('ix_Orders_Table_total_amount'), table_name='Orders_Table')
    op.drop_index(op.f('ix_Orders_Table_order_id'), table_name='Orders_Table')
    op.drop_table('Orders_Table')
    op.drop_table('Menu_Table')
    op.drop_table('User_Table')
    op.drop_index(op.f('ix_Restaurent_Table_Restaurent_rating'), table_name='Restaurent_Table')
    op.drop_index(op.f('ix_Restaurent_Table_Restaurent_id'), table_name='Restaurent_Table')
    op.drop_table('Restaurent_Table')
    op.drop_index(op.f('ix_Items_Table_item_id'), table_name='Items_Table')
    op.drop_table('Items_Table')
    # ### end Alembic commands ###
