"""Models CHanged

Revision ID: a64b6e45ac19
Revises: a342767cce7a
Create Date: 2026-04-03 00:24:48.248336

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a64b6e45ac19'
down_revision: Union[str, Sequence[str], None] = 'a342767cce7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('User_Table', 'user_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('User_Table', 'user_phone',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               nullable=True)
    op.alter_column('User_Table', 'user_email',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               nullable=True)
    op.create_index(op.f('ix_User_Table_user_id'), 'User_Table', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_User_Table_user_id'), table_name='User_Table')
    op.alter_column('User_Table', 'user_email',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               nullable=False)
    op.alter_column('User_Table', 'user_phone',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               nullable=False)
    op.alter_column('User_Table', 'user_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
